id = "veld"
name = "Veld"
description = "Veld language support for Zed"
version = "0.1.4"
schema_version = 1
authors = ["Perry <aidanpj18@gmail.com>"]
repository = "https://github.com/APConduct/zed-veld"

[grammars.veld]
repository = "https://github.com/APConduct/tree-sitter-veld"
rev = "e7415fc3d1a233219eb4acd01fc06f06c37ca7d0"
